
maci_admin_view:
    path:  /view/{section}/{entity}/{action}/{id}/{relation}/{relAction}/{bridge}
    defaults: { _controller: MaciAdminBundle:View:view, section: false, entity: false, action: false, id: false, relation: false, relAction: false, bridge: false }

maci_admin_dashboard:
    path:  /view/{section}
    defaults: { _controller: MaciAdminBundle:View:view }

maci_admin_not_found:
    path:  /not-found
    defaults: { _controller: MaciAdminBundle:View:notFound }

maci_admin:
    path:  /
    defaults: { _controller: MaciAdminBundle:View:index }


# maci_admin_entity_form:
#     path:  /admin/entities/{entity}/{id}/edit
#     defaults: { _controller: MaciAdminBundle:Default:form }
#     requirements:
#         id: \d+

# maci_admin_entity_file_upload:
#     path:  /admin/entities/{entity}/{id}/fileUpload
#     defaults: { _controller: MaciAdminBundle:Default:fileUpload, id: 0 }

# maci_admin_entity_object:
#     path:  /admin/entities/{entity}/{id}/object
#     defaults: { _controller: MaciAdminBundle:Default:object, id: 0 }

# maci_admin_entity_remove:
#     path:  /admin/entities/{entity}/{id}/remove
#     defaults: { _controller: MaciAdminBundle:Default:remove }
#     requirements:
#         id: \d+

# maci_admin_entity_set_filters:
#     path:  /admin/entities/{entity}/set_filters
#     defaults: { _controller: MaciAdminBundle:Default:setFilters }
#     requirements:
#         _method: POST

# maci_admin_entity_remove_filters:
#     path:  /admin/entities/{entity}/remove_filters
#     defaults: { _controller: MaciAdminBundle:Default:removeFilters }

# maci_admin_entity_show:
#     path:  /admin/entities/{entity}/{id}
#     defaults: { _controller: MaciAdminBundle:Default:show }
#     requirements:
#         id: \d+

# maci_admin_entity_reorder:
#     path:  /admin/entities/{entity}/reorder
#     defaults: { _controller: MaciAdminBundle:Default:reorder }
#     requirements:
#         _method: POST

# maci_admin_entity_new:
#     path:  /admin/entities/{entity}/new
#     defaults: { _controller: MaciAdminBundle:Default:form, id: 0 }

# maci_admin_entity_trash:
#     path:  /admin/entities/{entity}/trash
#     defaults: { _controller: MaciAdminBundle:Default:trash }

# maci_admin_entity:
#     path:  /admin/entities/{entity}
#     defaults: { _controller: MaciAdminBundle:Default:list }

