

maci_admin_entity_file_upload:
    pattern:  /admin/{entity}/{id}/fileUpload
    defaults: { _controller: MaciAdminBundle:Default:fileUpload, id: 0 }

maci_admin_entity_item:
    pattern:  /admin/{entity}/{id}/item
    defaults: { _controller: MaciAdminBundle:Default:item }
    requirements:
        id: \d+

maci_admin_entity_object:
    pattern:  /admin/{entity}/{id}/object
    defaults: { _controller: MaciAdminBundle:Default:object, id: 0 }

maci_admin_entity_remove:
    pattern:  /admin/{entity}/{id}/remove
    defaults: { _controller: MaciAdminBundle:Default:remove }
    requirements:
        id: \d+

maci_admin_entity_form:
    pattern:  /admin/{entity}/{id}
    defaults: { _controller: MaciAdminBundle:Default:form }
    requirements:
        id: \d+

maci_admin_entity_new:
    pattern:  /admin/{entity}/new
    defaults: { _controller: MaciAdminBundle:Default:form, id: 0 }

maci_admin_entity_reorder:
    pattern:  /admin/{entity}/reorder
    defaults: { _controller: MaciAdminBundle:Default:reorder }

maci_admin_entity:
    pattern:  /admin/{entity}
    defaults: { _controller: MaciAdminBundle:Default:list }

maci_admin_homepage:
    pattern:  /admin
    defaults: { _controller: MaciAdminBundle:Default:index }
