

maci_admin_entity_form:
    pattern:  /admin/{entity}/{id}/edit
    defaults: { _controller: MaciAdminBundle:Default:form }
    requirements:
        id: \d+

maci_admin_entity_file_upload:
    pattern:  /admin/{entity}/{id}/fileUpload
    defaults: { _controller: MaciAdminBundle:Default:fileUpload, id: 0 }

maci_admin_entity_object:
    pattern:  /admin/{entity}/{id}/object
    defaults: { _controller: MaciAdminBundle:Default:object, id: 0 }

maci_admin_entity_remove:
    pattern:  /admin/{entity}/{id}/remove
    defaults: { _controller: MaciAdminBundle:Default:remove }
    requirements:
        id: \d+

maci_admin_entity_set_filters:
    pattern:  /admin/{entity}/set_filters
    defaults: { _controller: MaciAdminBundle:Default:setFilters }
    requirements:
        _method: POST

maci_admin_entity_remove_filters:
    pattern:  /admin/{entity}/remove_filters
    defaults: { _controller: MaciAdminBundle:Default:removeFilters }

maci_admin_entity_show:
    pattern:  /admin/{entity}/{id}
    defaults: { _controller: MaciAdminBundle:Default:show }
    requirements:
        id: \d+

maci_admin_entity_reorder:
    pattern:  /admin/{entity}/reorder
    defaults: { _controller: MaciAdminBundle:Default:reorder }
    requirements:
        _method: POST

maci_admin_entity_new:
    pattern:  /admin/{entity}/new
    defaults: { _controller: MaciAdminBundle:Default:form, id: 0 }

maci_admin_entity_trash:
    pattern:  /admin/{entity}/trash
    defaults: { _controller: MaciAdminBundle:Default:list, trash: true }

maci_admin_entity:
    pattern:  /admin/{entity}
    defaults: { _controller: MaciAdminBundle:Default:list }

maci_admin:
    pattern:  /admin
    defaults: { _controller: MaciAdminBundle:Default:index }
