
services:

    maci.admin:
        class: Maci\AdminBundle\Controller\AdminController
        arguments: ["@doctrine.orm.entity_manager","@security.authorization_checker","@session","@request_stack","@kernel","@form.factory","@form.registry","@router","@templating","%maci.admin.config%"]

    maci.admin.default:
        class: Maci\AdminBundle\Controller\DefaultController
        arguments: ["@doctrine.orm.entity_manager","@session","@request_stack","@maci.admin"]

    maci_admin.menu_builder:
        class: Maci\AdminBundle\Menu\AdminMenuBuilder
        arguments: ["@knp_menu.factory","@request_stack","@maci.admin"]
        tags:
            - { name: knp_menu.menu_builder, method: createEntitiesMenu, alias: admin_entities }
            - { name: knp_menu.menu_builder, method: createSectionsMenu, alias: admin_sections }
            - { name: knp_menu.menu_builder, method: createActionsMenu, alias: admin_actions }
            - { name: knp_menu.menu_builder, method: createItemActionsMenu, alias: admin_item_actions }
